### ISSUE TITLE
embed more social media platforms besides twitter + telegram

### ISSUE THREAD

**Issue by msramalho** [bellingcat/ukraine-timemap#16]
Although Twitter and Telegram represent the vast majority of sources we have for the events, there are a few other platforms for which we would like to add embed support, namely:
* youtube - for example CIV0143, 2022/03/01, maybe with [react-youtube](https://www.npmjs.com/package/react-youtube)
* instagram- for example CIV0133, 2022/02/28, maybe with [react-instagram-embed](https://www.npmjs.com/package/react-instagram-embed)

[current embeds are used here](https://github.com/bellingcat/ukraine-timemap/blob/3f5252dd87479a9fce18f7e8277149b234f031b8/src/components/controls/atoms/Media.js#L4-L5)

**Comment by fspoettel** [comment]
I would like to work on this in the coming days. @msramalho can you assign me the issue?

**Comment by ohcnivek** [comment]
I'd also like to help out!

**Comment by fspoettel** [comment]
Awesome, should we split up the work? I could take care of insta?

**Comment by msramalho** [comment]
Thanks for the interest in this one!

@fspoettel go for insta.

As for the youtube one, I'd say first to declare here can go ahead (just so there's not duplication of work), but @fspoettel feel free to give @ohcnivek a couple of days in case he wants to give it a go since he's a potential new contributor here (👋) and this is a good first issue.

**Comment by fspoettel** [comment]
sounds like a plan, thanks!

**Comment by ohcnivek** [comment]
it's my first time here! will try my best & follow up here if I need help 😄

**Comment by fspoettel** [comment]
I reviewed above instagram plugin and there is a major problem: it calls an `/oembed` endpoint on the FB Graph API to retrieve the embed html. In order to call this endpoint, we need:

 1. a meta API application and a client access token for the Graph API.
 2. a manual review of our "app" from Facebook to get that token ‼️

![image](https://user-images.githubusercontent.com/1682504/162148650-c3e84747-3580-4740-b2b0-cfd7d94cabd0.png)

I'm really confused how they plan to review the implementation before giving us a token to actually make it work.

Also, [apparently the endpoint the plugin uses](https://developers.facebook.com/docs/instagram/oembed/) is deprecated and the [documentation for the replacement endpoint](https://developers.facebook.com/docs/graph-api/reference/instagram-oembed/) broken.

---

Embedding individual instagram posts via the embed button in Instagram is not a problem as it calls the oauth endpoint for the user, so no access token is required. It might be possible to "hardcode" this embed code and thereby circumvent calling the graph api in the first place. This could be brittle depending on how often this API changes though.

**Comment by fspoettel** [comment]
@msramalho does bellingcat have a facebook graph application with required scopes already by any chance?

**Comment by fspoettel** [comment]
> I'd prefer to avoid using the graph API with credentials, and going for the 2nd option

Yes, I agree - it's nuts that Facebook hides this behind a very restricted api scope.

>  even though from what I understand visitors not logged to instagram will not see the post (?)

**If** Facebook allows us to construct an embed string manually w/o first calling the oembed API, then everyone should be able to see these embeds. The main :question: is whether or not Facebook requires a call to the `oembed` API before it allows displaying a given posts as an embed. I need to test it to give a definite answer.

**Comment by msramalho** [comment]
Thanks for looking into it, happy it works as we wanted.

**Comment by ZLester** [comment]
Also interested in assisting if there are any more embeds that need to be done.

**Comment by msramalho** [comment]
Following up on the discussion in PR #39 I am indeed concern if some of these embeddings need to bring in scripts from 3rd parties and especially those with tracking capabilities. I would like to encourage some more discussion on that here, but the simplest way that already always users access to all links is a simple button that redirects to the original post. 
Happy to hear your thoughts @fspoettel and @wattroll

**Comment by fspoettel** [comment]
Fromg a GDPR and tracking perspective, an iframe is as bad as a script embed. there is no difference. both require consent and a privacy policy.

**Comment by fspoettel** [comment]
Personally, I think these embeds add a lot of value to the map as less context switching is required to assess events. It would be great to have a toggle "Show Embeds" in the source panel that converts "plain" links to real embeds so that 3rd party content (iframes and scripts) is only loaded on user request.

As mentioned in the Insta PR, their embed is a styled placeholder link so this might be one way to go UX-wise.

**Comment by msramalho** [comment]
I also agree that the previews add a lot of value to the map and that if they are not shown by default users might have a worse experience (knowing the toggle exists + using it is not straightforward), but I am not a fan of injecting scripts outside iframes. 

As for privacy/gdpr concerns, I'm curious whether we could have some additional message on the intro panel that would cover that or if it actually requires something like an "accept" button.

**Comment by fspoettel** [comment]
Alright, I'll close the PR then - I don't think there's a way to embed instagram in an iframe. It would be great to document expectations like this so people don't waste their time.

**Comment by fspoettel** [comment]
As for GDPR:
 - you need an explicit _Consent_ if the underlying iframe sets cookies. some embeds have a `noCookie` param or domain in which case you don't. Telegram and Twitter both set cookies so you need consent here.
 - All external data connections need to be documented in a _privacy policy_. Anything making a connection to a service not owned by Bellingcat would need to be documented here. This includes stuff like Google Fonts (yes, really).

The use of the injected Google TagManager script w/o consent is a direct violation of GDPR as well.

**Comment by msramalho** [comment]
Hi @fspoettel thanks for being so thorough, we will take these into account and try to fix it soon. 
And apologies for blocking your instagram contribution for now, I know that's not a pleasant contributor experience.
