### ISSUE TITLE
Add total number of verified incidents to introduction panel

### ISSUE THREAD

**Issue by loganwilliams** [bellingcat/ukraine-timemap#6]
The introduction panel currently displays static content about the project. It would be good to have a top-line number of the total number of incidents on the map displayed in this intro panel as well.

**Comment by msramalho** [comment]
Also thinking that it could be useful to include the number of currently visible events in this panel: 

It could even say: `Seeing X events that occurred between` or `Seeing X/Y events that occurred between` where `X` is the currently visible number of events, and `Y` the total value. 

I'm making this suggestion since the cover text is coming from the config file and it might not be so easy to template it with values. 

![image](https://user-images.githubusercontent.com/19508417/159351569-67b62540-7f96-4788-bb55-60898eb064a8.png)

**Comment by breezykermo** [comment]
Again, this would be a welcome PR to the upstream! :-)
